apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  # dependsOn:
  #   - name: infra
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infra/cert-manager
  prune: true
